server:
  port: 8080

spring:
  application:
    name: member-api
  profiles:
    active: local

  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    member-slave:
      jdbc-url: jdbc:mysql://localhost:3307/dod_member?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: adminadmin
#      driver-class-name: org.mysql.cj.jdbc.Driver

    member-master:
      jdbc-url: jdbc:mysql://localhost:3307/dod_member?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: adminadmin
#      driver-class-name: org.mysql.cj.jdbc.Driver


