
spring:
  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    member-slave:
      jdbc-url: jdbc:mysql:aurora://dod-dev-instance-1.c2p40zyxldlp.us-east-2.rds.amazonaws.com:3306/dod_member?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: admin
      password: a1d2m3i4n5
      driver-class-name: org.mariadb.jdbc.Driver

    member-master:
      jdbc-url: jdbc:mysql:aurora://dod-dev-instance-1.c2p40zyxldlp.us-east-2.rds.amazonaws.com:3306/dod_member?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: admin
      password: a1d2m3i4n5
      driver-class-name: org.mariadb.jdbc.Driver
