
server:
  port: 8081

spring:
  application:
    name: content-api
  profiles:
    active: local

  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    content-slave:
      jdbc-url: jdbc:mysql://localhost:3306/dod_content?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnection=true
      username: root
      password: adminadmin
    #      driver-class-name: com.mysql.cj.jdbc.Driver

    content-master:
      jdbc-url: jdbc:mysql://localhost:3306/dod_content?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnection=true
      username: root
      password: adminadmin
#      driver-class-name: com.mysql.cj.jdbc.Driver


